CREATE DATABASE Pessoas;

USE Pessoas;

CREATE TABLE Pessoa
(
	idPessoa	INT PRIMARY KEY IDENTITY
	,Nome		VARCHAR(200) NOT NULL
);

CREATE TABLE Telefone
(
	 idTelefone	INT PRIMARY KEY IDENTITY
	,idPessoa	INT FOREIGN KEY REFERENCES Pessoa (idPessoa)
	,NUMERO		VARCHAR(200) NOT NULL
);

CREATE TABLE Email
(
	idEmail		INT PRIMARY KEY IDENTITY
	,idPessoa	INT FOREIGN KEY REFERENCES Pessoa (idPessoa)
	,email		VARCHAR(200) NOT NULL
);

CREATE TABLE CNH
(
	idCNH		INT PRIMARY KEY IDENTITY
	,idPessoa	INT FOREIGN KEY REFERENCES Pessoa (idPessoa)
	,Numero		VARCHAR(200) NOT NULL
);
